from yacs.config import CfgNode as CN
import os

root = os.getcwd()

_C = CN()


#TRAINING RESULTS
_C.FILE = CN()
_C.FILE.MODEL_SAVE_PATH = root + '/weights'


#TRAINING DEVICES
_C.DEVICE = CN()
_C.DEVICE.GPU = 0


#MODEL SETTINGS
_C.MODEL = CN()
_C.MODEL.INPUT.IMAGE_SIZE = 300


#ANCHOR SETTINGS
_C.ANCHORS = CN()
_C.MODEL.ANCHORS.FEATURE_MAPS = [(38, 38), (19, 19), (10, 10), (5, 5), (3, 3), (1, 1)]
_C.MODEL.ANCHORS.BOXES_PER_LOCATION = [4,6,6,6,4,4] #NUMBER OF BBOXES PROCUDED ON EACH FEATURE POINT FOR EACH FEATURE MAP
_C.MODEL.ANCHORS.OUT_CHANNELS = [512, 1024, 512, 256, 256, 256] #OUTPUT CHANNELS
_C.MODEL.ANCHORS.MIN_SIZES = [30, 60, 111, 162, 213, 264]
_C.MODEL.ANCHORS.MAX_SIZES = [60, 111, 162, 213, 264, 315]
_C.MODEL.ANCHORS.ASPECT_RATIOS = [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
_C.MODEL.ANCHORS.CLIP = True         
_C.MODEL.ANCHORS.THRESHOLD = 0.5     
_C.MODEL.ANCHORS.CENTER_VARIANCE = 0.1
_C.MODEL.ANCHORS.SIZE_VARIANCE = 0.2

#DATASET SETTINGS
_C.DATA = CN()
_C.DATA.DATASET = CN()
_C.DATA.DATASET.NUM_CLASSES = 21